### ISSUE TITLE
Binary compatibility checks should be re-enabled

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-pulsar#222]
### Issue description

Binary compatibility checks are currently disabled, but it was because there wasn't a previous release. Now that we have one, they should be re-enabled. I tried it locally and it finds some breaking changes.

**Comment by harissecic** [comment]
I'm not up-to-speed with these kinds of project builds so I'll have to learn more. I'm aware of it and I'll try to merge your build changes to my local stuff. Then maybe I find out what is causing breaks. I never got to a point to pass the build if I leave on binary checks.

**Comment by melix** [comment]
No worries. The binary compatibility checks are there to ensure that you don't publish a library with breaking changes un-intentionally. You can find some background [here](https://github.com/micronaut-projects/micronaut-build/wiki/Upgrade-guide#binary-breaking-changes-discovery).

There are basically 2 cases where the report can fail:

1. if there's no "previous version" of the library found. This [isn't the case anymore](https://repo1.maven.org/maven2/io/micronaut/pulsar/) so there's a baseline to compare to (off topic, if you click the link above you'll see that we accidentally published test modules, this is fixed by the changes I made to the build. You can always verify what's going to be published by running `./gradlew publishAllPublicationsToBuildRepository` or `./gradlew pAPTBR` and check the contents of `build/repo`).
2. if there's a detected binary breaking change. In this case, you must look at the report: it's going to tell you what broke. Sometimes, you will want to accept the regressions. This is typically the case when you add a default implementation to an interface method, since it's a low risk breaking change, but a breaking change in any case. To accept regressions, you must accept them by adding the reasons in the json file. The report should always tell you what to do.

In any case, if it's unclear, don't hesitate to ping me or anyone else in the team.
